"""
models.py - Định nghĩa các model dữ liệu
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Union
from datetime import datetime
from enum import Enum
import hashlib
import json
import re


# ============================================================================
# ENUMS
# ============================================================================

class QuestionStatus(Enum):
    DRAFT = "draft"
    APPROVED = "approved"
    ARCHIVED = "archived"
    REJECTED = "rejected"


class ReviewStatus(Enum):
    """Review status cho câu hỏi được AI generate (V2)"""
    DRAFT = "DRAFT"  # Initial state
    AI_GENERATED = "AI_GENERATED"  # Generated by AI, needs review
    VERIFIED = "VERIFIED"  # Reviewed and approved
    REJECTED = "REJECTED"  # Reviewed and rejected


class ExamStatus(Enum):
    DRAFT = "draft"
    READY = "ready"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class ParamType(Enum):
    INTEGER = "integer"
    FLOAT = "float"
    CHOICE = "choice"
    RANGE = "range"
    BOOLEAN = "boolean"


# ============================================================================
# BASE MODELS
# ============================================================================

@dataclass
class BaseModel:
    """Base class cho các model"""
    id: Optional[int] = None
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> Dict:
        """Chuyển đổi sang dictionary"""
        raise NotImplementedError


# ============================================================================
# SUBJECT
# ============================================================================

@dataclass
class Subject(BaseModel):
    """Môn học"""
    name: str = ""
    code: str = ""
    description: str = ""
    is_active: bool = True
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "name": self.name,
            "code": self.code,
            "description": self.description,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None
        }


# ============================================================================
# CATEGORY
# ============================================================================

@dataclass
class Category(BaseModel):
    """Chủ đề/Chương - hỗ trợ phân cấp"""
    subject_id: Optional[int] = None  # Liên kết với môn học
    name: str = ""
    description: str = ""
    parent_id: Optional[int] = None
    level: int = 0
    sort_order: int = 0
    is_active: bool = True
    
    # Cached children (không lưu DB)
    children: List['Category'] = field(default_factory=list)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "subject_id": self.subject_id,
            "name": self.name,
            "description": self.description,
            "parent_id": self.parent_id,
            "level": self.level,
            "sort_order": self.sort_order,
            "is_active": self.is_active
        }
    
    def get_full_path(self) -> str:
        """Lấy đường dẫn đầy đủ (vd: Giải tích > Tích phân > Tích phân xác định)"""
        # Cần implement với parent lookup
        return self.name


# ============================================================================
# PARAMETER DEFINITION
# ============================================================================

@dataclass
class ParamDefinition:
    """Định nghĩa một tham số trong template"""
    name: str
    param_type: str = "integer"  # integer, float, choice, range, boolean
    
    # Constraints
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    step: Optional[float] = None  # Bước nhảy (cho range)
    choices: Optional[List[Any]] = None  # Danh sách giá trị cho choice
    exclude: Optional[List[Any]] = None  # Giá trị loại trừ
    default_value: Optional[Any] = None
    
    # Metadata
    description: str = ""
    display_name: str = ""  # Tên hiển thị
    unit: str = ""  # Đơn vị (nếu có)
    
    # Ảnh hưởng đến độ khó
    difficulty_weight: float = 0.0  # Trọng số ảnh hưởng độ khó
    
    def validate(self, value: Any) -> tuple[bool, str]:
        """
        Kiểm tra giá trị có hợp lệ không
        Returns: (is_valid, error_message)
        """
        # Kiểm tra exclude
        if self.exclude and value in self.exclude:
            return False, f"Giá trị {value} nằm trong danh sách loại trừ"
        
        if self.param_type == "integer":
            if not isinstance(value, int):
                return False, f"Giá trị phải là số nguyên, nhận được {type(value)}"
            if self.min_value is not None and value < self.min_value:
                return False, f"Giá trị {value} nhỏ hơn min ({self.min_value})"
            if self.max_value is not None and value > self.max_value:
                return False, f"Giá trị {value} lớn hơn max ({self.max_value})"
                
        elif self.param_type == "float":
            if not isinstance(value, (int, float)):
                return False, f"Giá trị phải là số, nhận được {type(value)}"
            if self.min_value is not None and value < self.min_value:
                return False, f"Giá trị {value} nhỏ hơn min ({self.min_value})"
            if self.max_value is not None and value > self.max_value:
                return False, f"Giá trị {value} lớn hơn max ({self.max_value})"
                
        elif self.param_type == "choice":
            if self.choices and value not in self.choices:
                return False, f"Giá trị {value} không nằm trong danh sách cho phép"
                
        elif self.param_type == "boolean":
            if not isinstance(value, bool):
                return False, f"Giá trị phải là boolean"
        
        return True, ""
    
    def get_valid_values(self) -> List[Any]:
        """Lấy danh sách tất cả giá trị hợp lệ"""
        values = []
        
        if self.param_type == "choice" and self.choices:
            values = list(self.choices)
            
        elif self.param_type == "integer":
            min_v = int(self.min_value) if self.min_value is not None else -10
            max_v = int(self.max_value) if self.max_value is not None else 10
            step = int(self.step) if self.step else 1
            values = list(range(min_v, max_v + 1, step))
            
        elif self.param_type == "boolean":
            values = [True, False]
            
        elif self.param_type == "float":
            # Với float, trả về một số giá trị mẫu
            min_v = float(self.min_value) if self.min_value is not None else -10.0
            max_v = float(self.max_value) if self.max_value is not None else 10.0
            step = float(self.step) if self.step else 1.0
            v = min_v
            while v <= max_v:
                values.append(v)
                v += step
        
        # Loại bỏ các giá trị exclude
        if self.exclude:
            values = [v for v in values if v not in self.exclude]
        
        return values
    
    def to_dict(self) -> Dict:
        return {
            "name": self.name,
            "type": self.param_type,
            "min": self.min_value,
            "max": self.max_value,
            "step": self.step,
            "choices": self.choices,
            "exclude": self.exclude,
            "default": self.default_value,
            "description": self.description,
            "display_name": self.display_name,
            "difficulty_weight": self.difficulty_weight
        }
    
    @classmethod
    def from_dict(cls, name: str, data: Dict) -> 'ParamDefinition':
        return cls(
            name=name,
            param_type=data.get('type', 'integer'),
            min_value=data.get('min'),
            max_value=data.get('max'),
            step=data.get('step'),
            choices=data.get('choices'),
            exclude=data.get('exclude'),
            default_value=data.get('default'),
            description=data.get('description', ''),
            display_name=data.get('display_name', name),
            difficulty_weight=data.get('difficulty_weight', 0.0)
        )


# ============================================================================
# TEMPLATE
# ============================================================================

@dataclass
class Template(BaseModel):
    """Template câu hỏi - dạng bài tham số hóa"""
    subject_id: Optional[int] = None  # Liên kết với môn học
    category_id: Optional[int] = None
    code: str = ""  # Mã định danh duy nhất (vd: INT_XN_EXP)
    name: str = ""
    description: str = ""
    
    # Công thức toán học (LaTeX với placeholder)
    # Placeholder format: {{{param_name}}}
    math_formula: str = ""
    
    # Template câu hỏi (có thể chứa placeholder)
    question_template: str = ""
    
    # Định nghĩa tham số
    param_schema: Dict[str, ParamDefinition] = field(default_factory=dict)
    
    # Metadata
    difficulty_base: int = 3  # Độ khó cơ bản (1-5)
    estimated_time: int = 3  # Thời gian ước tính (phút)
    tags: List[str] = field(default_factory=list)
    hints: List[str] = field(default_factory=list)
    
    # Trạng thái
    is_active: bool = True
    is_verified: bool = False
    
    # Audit
    created_by: Optional[int] = None
    
    def validate_params(self, params: Dict[str, Any]) -> tuple[bool, str]:
        """Kiểm tra bộ tham số có hợp lệ không"""
        for name, definition in self.param_schema.items():
            if name not in params:
                if definition.default_value is None:
                    return False, f"Thiếu tham số bắt buộc: {name}"
                # Sử dụng giá trị mặc định
                params[name] = definition.default_value
            else:
                is_valid, error = definition.validate(params[name])
                if not is_valid:
                    return False, f"Tham số {name}: {error}"
        return True, ""
    
    def render_formula(self, params: Dict[str, Any]) -> str:
        """Render công thức với tham số cụ thể"""
        formula = self.math_formula
        for name, value in params.items():
            # Xử lý hiển thị số âm
            if isinstance(value, (int, float)) and value < 0:
                display_value = f"({value})"
            else:
                display_value = str(value)
            formula = formula.replace(f"{{{{{name}}}}}", display_value)
        return formula
    
    def render_question(self, params: Dict[str, Any]) -> str:
        """Render câu hỏi với tham số"""
        if self.question_template:
            question = self.question_template
            for name, value in params.items():
                question = question.replace(f"{{{{{name}}}}}", str(value))
            return question
        else:
            # Mặc định: tính giá trị của công thức
            formula = self.render_formula(params)
            return f"Tính $\\displaystyle {formula}$"
    
    def get_total_combinations(self) -> int:
        """Tính tổng số tổ hợp tham số có thể"""
        total = 1
        for definition in self.param_schema.values():
            values = definition.get_valid_values()
            if values:
                total *= len(values)
        return total
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "code": self.code,
            "category_id": self.category_id,
            "name": self.name,
            "description": self.description,
            "math_formula": self.math_formula,
            "question_template": self.question_template,
            "param_schema": {
                name: p.to_dict() for name, p in self.param_schema.items()
            },
            "difficulty_base": self.difficulty_base,
            "estimated_time": self.estimated_time,
            "tags": self.tags,
            "hints": self.hints,
            "is_active": self.is_active,
            "is_verified": self.is_verified,
            "total_combinations": self.get_total_combinations()
        }


# ============================================================================
# DISTRACTOR CONFIG
# ============================================================================

@dataclass
class DistractorConfig:
    """Cấu hình sinh đáp án nhiễu"""
    strategies: List[str] = field(default_factory=lambda: [
        "sign_error", "missing_bound", "coefficient_error"
    ])
    count: int = 3  # Số đáp án nhiễu cần sinh
    validate_distinctness: bool = True  # Kiểm tra các đáp án khác nhau
    min_difference: float = 0.01  # Sai khác tối thiểu (với số thực)
    
    # Cấu hình cho từng chiến lược
    strategy_weights: Dict[str, float] = field(default_factory=dict)
    strategy_params: Dict[str, Dict] = field(default_factory=dict)


# ============================================================================
# TEST CASE
# ============================================================================

@dataclass
class TestCase:
    """Test case cho solver"""
    input_params: Dict[str, Any]
    expected_output: str  # Biểu thức kỳ vọng (dạng string)
    description: str = ""
    tolerance: float = 1e-10  # Sai số cho phép (với số thực)
    
    def to_dict(self) -> Dict:
        return {
            "input": self.input_params,
            "expected": self.expected_output,
            "description": self.description,
            "tolerance": self.tolerance
        }


# ============================================================================
# SOLVER
# ============================================================================

@dataclass
class Solver(BaseModel):
    """Code giải cho template"""
    template_id: int = 0
    version: str = "1.0.0"
    
    # Code
    language: str = "python"  # python, sympy, maxima
    code: str = ""
    entry_function: str = "solve"  # Tên hàm chính
    dependencies: List[str] = field(default_factory=list)
    
    # Cấu hình sinh đáp án nhiễu
    distractor_config: DistractorConfig = field(default_factory=DistractorConfig)
    
    # Cấu hình sinh lời giải
    solution_template: str = ""  # Template lời giải
    
    # Test cases
    test_cases: List[TestCase] = field(default_factory=list)
    
    # Trạng thái
    is_active: bool = True
    is_validated: bool = False
    validation_log: str = ""
    last_validated_at: Optional[datetime] = None
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "template_id": self.template_id,
            "version": self.version,
            "language": self.language,
            "entry_function": self.entry_function,
            "dependencies": self.dependencies,
            "distractor_config": {
                "strategies": self.distractor_config.strategies,
                "count": self.distractor_config.count
            },
            "test_cases": [tc.to_dict() for tc in self.test_cases],
            "is_active": self.is_active,
            "is_validated": self.is_validated
        }


# ============================================================================
# ANSWER
# ============================================================================

@dataclass
class Answer:
    """Một đáp án trong câu hỏi trắc nghiệm"""
    text: str  # Hiển thị cho user
    latex: str = ""  # Phiên bản LaTeX
    value: Any = None  # Giá trị thực (để so sánh)
    symbolic: str = ""  # Biểu thức symbolic (string)
    is_correct: bool = False
    error_type: Optional[str] = None  # Loại lỗi (nếu là đáp án sai)
    error_description: str = ""  # Mô tả lỗi
    
    def to_dict(self) -> Dict:
        return {
            "text": self.text,
            "latex": self.latex,
            "symbolic": self.symbolic,
            "is_correct": self.is_correct,
            "error_type": self.error_type
        }


# ============================================================================
# QUESTION
# ============================================================================

@dataclass
class Question(BaseModel):
    """Câu hỏi đã sinh"""
    template_id: int = 0
    solver_id: Optional[int] = None
    
    # Tham số
    param_values: Dict[str, Any] = field(default_factory=dict)
    param_hash: str = ""  # Hash của param_values để check trùng
    
    # Nội dung
    question_text: str = ""
    question_latex: str = ""
    question_html: str = ""
    
    # Đáp án
    answers: Dict[str, Answer] = field(default_factory=dict)  # A, B, C, D
    correct_answer: str = ""  # 'A', 'B', 'C', 'D'
    correct_value: Any = None
    correct_symbolic: str = ""
    
    # Lời giải
    solution: str = ""
    solution_latex: str = ""
    solution_steps: List[str] = field(default_factory=list)
    
    # NEW (V2): AI Enrichment & Explanation
    explanation: str = ""  # Lời giải chi tiết từ AI
    explanation_latex: str = ""  # LaTeX version của explanation
    ai_enriched: bool = False  # Flag: có được AI làm giàu không
    review_status: Optional[str] = None  # ReviewStatus enum value (DRAFT, AI_GENERATED, VERIFIED, REJECTED)
    
    # Metadata
    difficulty: int = 3
    quality_score: float = 0.0
    estimated_time: int = 3  # phút
    
    # Trạng thái
    status: QuestionStatus = QuestionStatus.DRAFT
    is_active: bool = True
    
    # Review
    reviewed_by: Optional[int] = None
    reviewed_at: Optional[datetime] = None
    review_notes: str = ""
    
    # Thống kê
    usage_count: int = 0
    last_used_at: Optional[datetime] = None
    correct_rate: float = 0.0  # Tỷ lệ trả lời đúng (nếu có thống kê)
    
    @staticmethod
    def compute_param_hash(param_values: Dict[str, Any]) -> str:
        """Tính hash của bộ tham số để check trùng"""
        # Sort keys để đảm bảo deterministic
        sorted_params = json.dumps(param_values, sort_keys=True)
        return hashlib.sha256(sorted_params.encode()).hexdigest()[:16]
    
    def __post_init__(self):
        if not self.param_hash and self.param_values:
            self.param_hash = self.compute_param_hash(self.param_values)
    
    def get_correct_answer_text(self) -> str:
        """Lấy text của đáp án đúng"""
        if self.correct_answer in self.answers:
            return self.answers[self.correct_answer].text
        return ""
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "template_id": self.template_id,
            "param_values": self.param_values,
            "param_hash": self.param_hash,
            "question_text": self.question_text,
            "answers": {
                letter: ans.to_dict() for letter, ans in self.answers.items()
            },
            "correct_answer": self.correct_answer,
            "solution": self.solution,
            "difficulty": self.difficulty,
            "status": self.status.value if isinstance(self.status, QuestionStatus) else self.status,
            "usage_count": self.usage_count
        }
    
    def to_display_dict(self, show_answer: bool = False) -> Dict:
        """Format để hiển thị cho user"""
        result = {
            "id": self.id,
            "question": self.question_text,
            "answers": {
                letter: ans.text for letter, ans in self.answers.items()
            },
            "difficulty": self.difficulty
        }
        if show_answer:
            result["correct_answer"] = self.correct_answer
            result["solution"] = self.solution
        return result


# ============================================================================
# EXAM CONFIG
# ============================================================================

@dataclass
class ExamConfig:
    """Cấu hình đề thi"""
    total_questions: int = 30
    duration_minutes: int = 60
    passing_score: float = 50.0  # Điểm đạt (%)
    
    # Xáo trộn
    shuffle_questions: bool = True
    shuffle_answers: bool = True
    
    # Phân bố theo độ khó
    difficulty_distribution: Dict[int, int] = field(default_factory=dict)
    # Ví dụ: {1: 5, 2: 10, 3: 10, 4: 3, 5: 2} = 5 câu dễ, 10 câu TB, ...
    
    # Phân bố theo chủ đề
    category_distribution: Dict[int, int] = field(default_factory=dict)
    # Ví dụ: {3: 15, 2: 15} = 15 câu tích phân, 15 câu đạo hàm
    
    # Phân bố theo template
    template_distribution: Dict[int, int] = field(default_factory=dict)
    
    # Constraints
    no_repeat_questions: bool = True  # Không lặp câu hỏi
    exclude_question_ids: List[int] = field(default_factory=list)  # Loại trừ câu hỏi
    exclude_exam_ids: List[int] = field(default_factory=list)  # Không dùng câu từ đề cũ
    
    def to_dict(self) -> Dict:
        return {
            "total_questions": self.total_questions,
            "duration_minutes": self.duration_minutes,
            "passing_score": self.passing_score,
            "shuffle_questions": self.shuffle_questions,
            "shuffle_answers": self.shuffle_answers,
            "difficulty_distribution": self.difficulty_distribution,
            "category_distribution": self.category_distribution,
            "template_distribution": self.template_distribution
        }


# ============================================================================
# EXAM QUESTION
# ============================================================================

@dataclass
class ExamQuestion:
    """Câu hỏi trong đề thi"""
    id: Optional[int] = None
    exam_id: int = 0
    question_id: int = 0
    position: int = 0  # Thứ tự trong đề
    points: float = 1.0  # Điểm của câu
    
    # Mapping đáp án sau khi xáo trộn
    # Ví dụ: {"A": "C", "B": "A", "C": "D", "D": "B"}
    # Nghĩa là đáp án gốc A hiển thị ở vị trí C
    answer_mapping: Dict[str, str] = field(default_factory=dict)
    
    def get_displayed_correct_answer(self, original_correct: str) -> str:
        """Lấy đáp án đúng sau khi xáo trộn"""
        return self.answer_mapping.get(original_correct, original_correct)


# ============================================================================
# EXAM
# ============================================================================

@dataclass
class Exam(BaseModel):
    """Đề thi"""
    code: str = ""  # Mã đề thi
    name: str = ""
    description: str = ""
    
    # Cấu hình
    config: ExamConfig = field(default_factory=ExamConfig)
    
    # Danh sách câu hỏi
    questions: List[ExamQuestion] = field(default_factory=list)
    
    # Trạng thái
    status: ExamStatus = ExamStatus.DRAFT
    is_published: bool = False
    published_at: Optional[datetime] = None
    
    # Audit
    created_by: Optional[int] = None
    
    # Thống kê (sau khi sử dụng)
    times_used: int = 0
    average_score: float = 0.0
    
    def get_total_points(self) -> float:
        """Tính tổng điểm của đề"""
        return sum(eq.points for eq in self.questions)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "code": self.code,
            "name": self.name,
            "description": self.description,
            "config": self.config.to_dict(),
            "total_questions": len(self.questions),
            "total_points": self.get_total_points(),
            "status": self.status.value if isinstance(self.status, ExamStatus) else self.status,
            "is_published": self.is_published
        }


# ============================================================================
# GENERATION LOG
# ============================================================================

@dataclass
class GenerationLog(BaseModel):
    """Log sinh câu hỏi"""
    template_id: int = 0
    solver_id: Optional[int] = None
    batch_id: str = ""  # ID của batch (nếu sinh hàng loạt)
    
    param_values: Dict[str, Any] = field(default_factory=dict)
    
    # Kết quả
    status: str = ""  # success, failed, skipped, duplicate
    question_id: Optional[int] = None
    error_message: str = ""
    
    # Performance
    execution_time: float = 0.0  # Thời gian thực thi (giây)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "template_id": self.template_id,
            "batch_id": self.batch_id,
            "param_values": self.param_values,
            "status": self.status,
            "question_id": self.question_id,
            "error_message": self.error_message,
            "execution_time": self.execution_time
        }


# ============================================================================
# USER (Optional - nếu cần quản lý người dùng)
# ============================================================================

@dataclass
class User(BaseModel):
    """Người dùng hệ thống"""
    username: str = ""
    email: str = ""
    full_name: str = ""
    role: str = "user"  # admin, teacher, user
    is_active: bool = True
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "username": self.username,
            "email": self.email,
            "full_name": self.full_name,
            "role": self.role,
            "is_active": self.is_active
        }
